Header comments for backend and dummy
bytecraftoy/aalto-2022 pull request #161
Opened 2023-03-18 12:33 UTC by hmalmsten

Our Definition of Done requires all our code files contain a header comment describing the comments of the file.

Someone with higher understanding of the files in the frontend should do the same there.

2023-03-23 16:49 UTC, jniemii requested changes, later dismissed
please fix the extra diffs from unrelated commits.

2023-03-25 16:14 UTC, KorpelainenTommi approved these changes

2023-03-25 18:42 UTC, jniemii approved these changes

2023-03-26 13:11 UTC, jaakkojari approved these changes
lgtm

2023-03-27 08:58 UTC, merged