registration key is now read from the url
bytecraftoy/aalto-2022 pull request #178
Opened 2023-04-14 13:47 UTC by itulkki

2023-04-14 13:52 UTC, jaakkojari approved these changes
Lgtm

2023-04-15 12:24 UTC, KorpelainenTommi requested changes
React Router contains a hook called `useSearchParams` which accomplishes the same results as `getQueryParameters`.

e.g.
`const [params] = useSearchParams();`
`const key = params.get('key'); // key is string | null`

2023-04-15 12:40 UTC, KorpelainenTommi approved these changes

2023-04-15 13:14 UTC, hmalmsten approved these changes

2023-04-16 10:44 UTC, merged