Segmented button
bytecraftoy/aalto-2022 pull request #22
Opened 2022-11-24 15:29 UTC by samikuikka

Created reusable segmented button that can be used to create export buttons of the content panel

2022-11-25 06:44 UTC, KorpelainenTommi commented on frontend/src/components/Buttons/SegmentedButton/SegmentedButton.tsx/index.tsx
> +export const SegemnetdButton: React.FC<SegmentedButtonProps> = ({
typo

2022-11-25 06:52 UTC, KorpelainenTommi requested changes
Folder structure should be changed,
SegmentedButton/SegmentedButton.tsx/index.tsx
=> SegmentedButtons/SegmentedButton/index.tsx

There is also a typo which should be fixed:
SegmentedButton/SegmentedButton.tsx/index.tsx
line 15
`export const SegemnetdButton` => `export const SegmentedButton`

2022-11-25 09:11 UTC, jaakkoha-bytecraft commented
https://github.com/bytecraftoy/aalto-2022/pull/23 I posted a bunch of comments here.

2022-11-26 13:53 UTC, KorpelainenTommi approved these changes

2022-11-27 03:58 UTC, merged