Db queries file
bytecraftoy/aalto-2022 pull request #80
Opened 2023-01-23 17:21 UTC by hmalmsten

2023-01-23 18:08 UTC, jniemii approved these changes
The return value of executeQuery probably isn't correct but we can fix it later

2023-01-24 06:33 UTC, itulkki commented on backend/src/db/queries.ts
> +    };
this could be written simply as
const query = {text, values};

2023-01-24 06:38 UTC, itulkki requested changes, later dismissed
Please add some comments explaining what happens if the queries are unsuccessful in some way

2023-01-25 09:01 UTC, jaakkoha-bytecraft commented on backend/src/db/queries.ts
> +const selectProjectsbyUserID = async (userID: string) => {
These should be `export const ...` and contain a return type, since right now all of these will return `any`.

2023-01-25 10:15 UTC, hmalmsten commented
> Please add some comments explaining what happens if the queries are unsuccessful in some way

It seems @jniemii has error handling for this resolved in a child branch

2023-01-26 09:10 UTC, jaakkoha-bytecraft approved these changes

2023-01-26 09:12 UTC, merged